name: meson build & test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Update package data
      run: sudo apt update
    - name: Install devel packages
      run: sudo apt-get install libpam0g-dev libsqlite3-dev meson ninja-build
    - uses: actions/checkout@v7
    - name: Setup
      run: meson setup build
    - name: Build
      run: meson compile -C build --verbose
    - name: Test
      run: meson test -C build --verbose
